import sys
import argparse

import parse_cat
import range_list


def cat_is_zero(cat):
    if cat == 'Mc': return True
    if cat == 'Me': return True
    return False


parser = argparse.ArgumentParser(description='Generate zero width table')
parser.add_argument('--input', required=True)
parser.add_argument('--output', required=True)

args = parser.parse_args()

general_category = parse_cat.parse(args.input)
zero_width_table = range_list.transform_list(general_category, cat_is_zero)

with open(args.output, 'w') as output:
    print(f'// This file was generated by {__file__}');
    count = 0
    for w in zero_width_table:
        if w.property:
            print(f'{{ {w.range_start:#7x}, {w.range_end:#7x} }},', end='', file=output)

            count += 1
            if count % 3 == 0:
                print(end='\n', file=output)
            else:
                print(' ', end='', file=output)

    print(end='\n', file=output)
